### ISSUE TITLE
Fix Phoenix example's seed data step

### ISSUE THREAD

**Issue by steveluscher** [steveluscher/zero-to-graphql#10]
When I run `mix ecto.seed` I see this:

```
** (ArgumentError) validate_required/3 expects field names to be atoms, got: `"person_id"`
    (ecto) lib/ecto/changeset.ex:1140: Ecto.Changeset.missing?/2
    (ecto) lib/ecto/changeset.ex:1115: anonymous fn/5 in Ecto.Changeset.validate_required/3
    (elixir) lib/enum.ex:1778: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/changeset.ex:1114: Ecto.Changeset.validate_required/3
    priv/repo/seeds.exs:28: (file)
    (elixir) lib/code.ex:376: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:94: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:54: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:333: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:266: Mix.Task.run/2
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

Furthermore, no friend relationships appear in my graph when I execute such a query in GraphiQL.

**Comment by steveluscher** [comment]
cc/ @conradwt

**Comment by conradwt** [comment]
@steveluscher Thanks for the update and this issue has been fixed in PR #16 .
